// <auto-generated />
using System;
using AirbnbClone.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AirBnb.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AirBnb.Data.Availability", b =>
                {
                    b.Property<int>("aid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("aid"));

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("is_blocked")
                        .HasColumnType("boolean");

                    b.Property<int>("listId")
                        .HasColumnType("integer");

                    b.HasKey("aid");

                    b.HasIndex("listId");

                    b.ToTable("Availabilities");
                });

            modelBuilder.Entity("AirBnb.Data.Listing", b =>
                {
                    b.Property<int>("listId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("listId"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("amenities")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("bathroom_count")
                        .HasColumnType("integer");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("hostId")
                        .HasColumnType("integer");

                    b.Property<bool>("is_active")
                        .HasColumnType("boolean");

                    b.Property<decimal>("latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("longitude")
                        .HasColumnType("numeric");

                    b.Property<int>("max_guests")
                        .HasColumnType("integer");

                    b.Property<decimal>("price_per_knight")
                        .HasColumnType("numeric");

                    b.Property<string>("property_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("room_count")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("listId");

                    b.HasIndex("hostId");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("AirBnb.Data.ListingImage", b =>
                {
                    b.Property<int>("imageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("imageId"));

                    b.Property<string>("image_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_cover")
                        .HasColumnType("boolean");

                    b.Property<int>("listId")
                        .HasColumnType("integer");

                    b.Property<int>("sort_order")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("imageId");

                    b.HasIndex("listId");

                    b.ToTable("ListingImages");
                });

            modelBuilder.Entity("AirBnb.Data.Payment", b =>
                {
                    b.Property<int>("paymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("paymentId"));

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("paid_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("provider_response")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("provider_tx_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("reservationId")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("paymentId");

                    b.HasIndex("reservationId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("AirBnb.Data.Reservation", b =>
                {
                    b.Property<int>("reservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("reservationId"));

                    b.Property<DateTime>("check_in")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("check_out")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("guestId")
                        .HasColumnType("integer");

                    b.Property<int>("guest_count")
                        .HasColumnType("integer");

                    b.Property<int>("listId")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("total_price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("reservationId");

                    b.HasIndex("guestId");

                    b.HasIndex("listId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("AirBnb.Data.Review", b =>
                {
                    b.Property<int>("reviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("reviewId"));

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("listingId")
                        .HasColumnType("integer");

                    b.Property<int>("rating")
                        .HasColumnType("integer");

                    b.Property<int>("reservationId")
                        .HasColumnType("integer");

                    b.Property<int>("reviewerId")
                        .HasColumnType("integer");

                    b.HasKey("reviewId");

                    b.HasIndex("listingId");

                    b.HasIndex("reservationId");

                    b.HasIndex("reviewerId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("AirBnb.Data.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("userId"));

                    b.Property<string>("avatar_url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_verified")
                        .HasColumnType("boolean");

                    b.Property<string>("lname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("userId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AirBnb.Data.Availability", b =>
                {
                    b.HasOne("AirBnb.Data.Listing", "listing")
                        .WithMany("availabilities")
                        .HasForeignKey("listId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("listing");
                });

            modelBuilder.Entity("AirBnb.Data.Listing", b =>
                {
                    b.HasOne("AirBnb.Data.User", "host")
                        .WithMany("hosted_listings")
                        .HasForeignKey("hostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("host");
                });

            modelBuilder.Entity("AirBnb.Data.ListingImage", b =>
                {
                    b.HasOne("AirBnb.Data.Listing", "listing")
                        .WithMany("listing_images")
                        .HasForeignKey("listId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("listing");
                });

            modelBuilder.Entity("AirBnb.Data.Payment", b =>
                {
                    b.HasOne("AirBnb.Data.Reservation", "reservation")
                        .WithOne("payment")
                        .HasForeignKey("AirBnb.Data.Payment", "reservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("reservation");
                });

            modelBuilder.Entity("AirBnb.Data.Reservation", b =>
                {
                    b.HasOne("AirBnb.Data.User", "guest")
                        .WithMany("guest_reservations")
                        .HasForeignKey("guestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AirBnb.Data.Listing", "listing")
                        .WithMany("reservations")
                        .HasForeignKey("listId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("guest");

                    b.Navigation("listing");
                });

            modelBuilder.Entity("AirBnb.Data.Review", b =>
                {
                    b.HasOne("AirBnb.Data.Listing", "listing")
                        .WithMany("reviews")
                        .HasForeignKey("listingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirBnb.Data.Reservation", "reservation")
                        .WithMany("reviews")
                        .HasForeignKey("reservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirBnb.Data.User", "reviewer")
                        .WithMany("written_reviews")
                        .HasForeignKey("reviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("listing");

                    b.Navigation("reservation");

                    b.Navigation("reviewer");
                });

            modelBuilder.Entity("AirBnb.Data.Listing", b =>
                {
                    b.Navigation("availabilities");

                    b.Navigation("listing_images");

                    b.Navigation("reservations");

                    b.Navigation("reviews");
                });

            modelBuilder.Entity("AirBnb.Data.Reservation", b =>
                {
                    b.Navigation("payment")
                        .IsRequired();

                    b.Navigation("reviews");
                });

            modelBuilder.Entity("AirBnb.Data.User", b =>
                {
                    b.Navigation("guest_reservations");

                    b.Navigation("hosted_listings");

                    b.Navigation("written_reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
